### ISSUE TITLE
Assign User Roles

### ISSUE THREAD

**Issue by dantebarbieri** [csce-cups/tias#23]
On sign-in, users should be directed to set their roles:

- Peer Teacher
- Teaching Assistant

These roles should be changeable on the profile page.

As far as Administrators and Professors, there must be a system for existing Administrators to nominate new ones. I am not sure how to handle Professors. This may be part of the scope that is cut, especially because Professors and TAs are more likely to be cut.

**Comment by dantebarbieri** [comment]
pls

**Comment by benbeauchamp7** [comment]
Handled in admin page #74
