### ISSUE TITLE
Change all URL components to be lowercase in order to follow convention.

### ISSUE THREAD

**Issue by Shane-McGookey** [csce-cups/tias#70]
e.g.,
![image](https://user-images.githubusercontent.com/60854560/162000435-ee078a11-1da1-4c54-bf69-abd019f9dad8.png)

To follow convention, let us make sure all routes are lowercase such that the URL remains wholly lowercase.

**Comment by dantebarbieri** [comment]
pls

**Comment by benbeauchamp7** [comment]
Closes with #74
