### ISSUE TITLE
On First Sign In, Two Accounts are Made

### ISSUE THREAD

**Issue by dantebarbieri** [csce-cups/tias#83]
When Evelyn and Jeremy first sign in, there are two accounts. This is an issue with how we generate new users in the database. Probably someone relying on `ON CONFLICT`, which does not trigger if there isn't a Unique constraint. I could add a constraint for `email`. Is that preferable?

**Comment by Shane-McGookey** [comment]
This turned out to be an issue with case-sensitive comparison. It should be resolved now (through case-insensitive comparison in the _postSession_ lambda).
