### ISSUE TITLE
Dr. Leyk Wants These

### ISSUE THREAD

**Issue by dantebarbieri** [csce-cups/tias#97]
- Features
  - [x] Manual Scheduling - Dropdowns on Blocks
  - [x] Preference Viewer - On Demand Per Person on Admin Page
  - [ ] Subscheduler - Schedule People for Certain Courses, Pulling or Nonpulling
  - [ ] Lockout Button - Maybe
- Changes
  - [x] Export in Alternate Format
  - [x] Schedule by Hours Ceiling Instead of # Labs Ceiling

**Comment by dantebarbieri** [comment]
My #101 PR addresses **Export in Alternate Format**, which can be checked on merge. I'm not sure whether it is a perfect fix because I'm having issues with local testing.

**Comment by benbeauchamp7** [comment]
#102 addresses the **Preference Viewer** feature, which can be checked on merge

**Comment by dantebarbieri** [comment]
#107 addresses the Schedule by Hours Ceiling change and has many other changes to the scheduler following Dr. Leyk's requests.
